#!/usr/bin/env bash
test -z "$LAG_CONFFILE" && LAG_CONFFILE=~/.lag
export lag
declare -A lag
. "$LAG_CONFFILE"
if [ "$#" -eq 0 ]; then
    me="$(realpath "$0")"
    for name in "${!lag[@]}"; do
        echo -n "alias "
        printf "%q" "$name"
        echo -n "='$me "
        printf "%q" "$name"
        echo "'"
    done
fi
if [ "$#" -eq 1 ]; then
    "$(ls -1 ${lag[$1]} | sort -V | tail -1)" "$@" &
fi
